### ISSUE TITLE
Steps towards making this possibly CRAN compliant

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppspdlog#1]
Initial attempts at just substituting `stdout` and `stderr` with `Rcpp::Rcout` and `Rcpp::Rcerr` lead nowhere, which is why this languished unfinished for too long.

Currently, the main branch has no compiled code :grin: leading to no warnings.  Very clever.

Branch [feature/with_src](https://github.com/eddelbuettel/rcppspdlog/tree/feature/with_src) has the simple `exampleFour.cpp` with its derived sink for Rcpp.  It still gets

```sh
* checking compiled code ... NOTE
File ‘RcppSpdlog/libs/RcppSpdlog.so’:
  Found ‘stderr’, possibly from ‘stderr’ (C)
    Object: ‘exampleFour.o’
  Found ‘stdout’, possibly from ‘stdout’ (C)
    Object: ‘exampleFour.o’

Compiled code should not call entry points which might terminate R nor write to stdout/stderr instead 
of to the console, nor use Fortran I/O nor system RNGs.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... OK
```

@gabime was kind enough to lend an ear over email, maybe we will get somewhere by capturing logging in an osstream object and passing that to R.  Sadly, there is also a little bit of `stdout` in the fmt library so not sure we will get there.

Help needed and welcome if someone wants to poke -- please get in touch.

**Comment by gabime** [comment]
Could this [line](https://github.com/gabime/spdlog/blob/685cc4edbc3b729d28238d849e76a4786e4d5517/include/spdlog/logger-inl.h#L250) be the cause of this warning?

**Comment by eddelbuettel** [comment]
You are _very very good_. I am not sure how I missed that in my attempts.   Now, the `stdout` and `stderr` checks are independent but we are now down to

```sh
* checking compiled code ... NOTE
File ‘RcppSpdlog/libs/RcppSpdlog.so’:
  Found ‘stdout’, possibly from ‘stdout’ (C)
    Object: ‘exampleFour.o’

Compiled code should not call entry points which might terminate R nor write to stdout/stderr instead
of to the console, nor use Fortran I/O nor system RNGs.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... OK
````

with this simple diff

```diff
edd@rob:~/git/rcppspdlog(feature/with_src)$ git diff inst/include/spdlog/logger-inl.h
diff --git a/inst/include/spdlog/logger-inl.h b/inst/include/spdlog/logger-inl.h
index 69d6a1d..da8147a 100644
--- a/inst/include/spdlog/logger-inl.h
+++ b/inst/include/spdlog/logger-inl.h
@@ -12,7 +12,7 @@
 #include <spdlog/pattern_formatter.h>
 
 #include <cstdio>
-
+#include <Rcpp.h>
 namespace spdlog {
 
 // public methods
@@ -247,7 +247,8 @@ SPDLOG_INLINE void logger::err_handler_(const std::string &msg)
         auto tm_time = details::os::localtime(system_clock::to_time_t(now));
         char date_buf[64];
         std::strftime(date_buf, sizeof(date_buf), "%Y-%m-%d %H:%M:%S", &tm_time);
-        fprintf(stderr, "[*** LOG ERROR #%04zu ***] [%s] [%s] {%s}\n", err_counter, date_buf, name().c_str(), msg.c_str());
+        //fprintf(stderr, "[*** LOG ERROR #%04zu ***] [%s] [%s] {%s}\n", err_counter, date_buf, name().c_str(), msg.c_str());
+        REprintf("[*** LOG ERROR #%04zu ***] [%s] [%s] {%s}\n", err_counter, date_buf, name().c_str(), msg.c_str());
     }
 }
 } // namespace spdlog
edd@rob:~/git/rcppspdlog(feature/with_src)$ 
```

Now for the remaining `stdout` or couple of them.

**Comment by gabime** [comment]
Please try to define SPDLOG_DISABLE_DEFAULT_LOGGER before including spdlog.h

This will prevent spdlog  the include for ansicolor_sink.h which might cause the last warning

**Comment by eddelbuettel** [comment]
Holy smokes.  That did it.  If you look at [src/exampleFour.cpp](https://github.com/eddelbuettel/rcppspdlog/blob/feature/with_src/src/exampleFour.cpp) I was already a bit more careful:

https://github.com/eddelbuettel/rcppspdlog/blob/da99c4a1558bb68d501d0c3f626cba575e0a4d84/src/exampleFour.cpp#L2-L11

but that now does it: 

```diff
edd@rob:~/git/rcppspdlog(feature/with_src)$ git diff src/exampleFour.cpp
diff --git a/src/exampleFour.cpp b/src/exampleFour.cpp
index 99fcff4..f770a0b 100644
--- a/src/exampleFour.cpp
+++ b/src/exampleFour.cpp
@@ -1,4 +1,5 @@
 
+#define SPDLOG_DISABLE_DEFAULT_LOGGER 1
 //#include "spdlog/spdlog.h"
 //#include "spdlog/sinks/stdout_color_sinks.h"
 #include <spdlog/details/synchronous_factory.h>
edd@rob:~/git/rcppspdlog(feature/with_src)$ 
```

Clean as a whistle:   
![image](https://user-images.githubusercontent.com/673121/90701423-00fb0a00-e24e-11ea-9a11-d83d1857dea4.png)

**Comment by eddelbuettel** [comment]
All good now and merged. Thanks again @gabime !
